package routers

import (
	"do-mall/controller/api/v1/AuthController"
	"do-mall/controller/api/v1/TagController"
	_ "do-mall/docs" // docs is generated by Swag CLI, you have to import it.
	jwt "do-mall/middleware"
	"do-mall/pkg/setting"
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

func InitRouter() *gin.Engine {
	r := gin.New()

	r.Use(gin.Logger())

	r.Use(gin.Recovery())

	gin.SetMode(setting.RunMode)

	r.GET("/test", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "test",
		})
	})

	// use ginSwagger middleware to
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.POST("/auth", AuthController.GetAuth)

	// 注册路由
	apiv1 := r.Group("/api/v1")
	apiv1.Use(jwt.JWT())
	{
		// Tag
		apiv1.GET("/tags", TagController.Get)
		apiv1.POST("/tag", TagController.Create)
		apiv1.DELETE("/tags/:id", TagController.Destroy)
		apiv1.PUT("/tags/:id", TagController.Update)

	}

	return r
}
